CREATE TABLE [dbo].[EURUSD_H4_TMP] (
    [<DATE>]    VARCHAR (50) NULL,
    [<TIME>]    VARCHAR (50) NULL,
    [<OPEN>]    VARCHAR (50) NULL,
    [<HIGH>]    VARCHAR (50) NULL,
    [<LOW>]     VARCHAR (50) NULL,
    [<CLOSE>]   VARCHAR (50) NULL,
    [<TICKVOL>] VARCHAR (50) NULL,
    [<VOL>]     VARCHAR (50) NULL,
    [<SPREAD>]  VARCHAR (50) NULL
);

