CREATE TABLE [dbo].[ResW] (
    [RowNo]                        BIGINT           NULL,
    [Time]                         VARCHAR (50)     NULL,
    [Open]                         DECIMAL (38, 5)  NULL,
    [High]                         DECIMAL (38, 5)  NULL,
    [Low]                          DECIMAL (38, 5)  NULL,
    [Close]                        DECIMAL (38, 5)  NULL,
    [CandleCeiling]                DECIMAL (38, 5)  NULL,
    [CandleFloor]                  DECIMAL (38, 5)  NULL,
    [Volume]                       INT              NULL,
    [DateID]                       INT              NULL,
    [MaxBetween]                   DECIMAL (38, 5)  NULL,
    [MinBetween]                   DECIMAL (38, 5)  NULL,
    [Endt]                         DATE             NULL,
    [MX]                           INT              NULL,
    [Min]                          INT              NULL,
    [EnDay]                        CHAR (2)         NULL,
    [EnMonthName]                  NVARCHAR (50)    NULL,
    [EnYear]                       CHAR (4)         NULL,
    [lgMax]                        DECIMAL (38, 5)  NULL,
    [LgMin]                        DECIMAL (38, 5)  NULL,
    [ClosePriceDiffLgMin]          DECIMAL (38, 5)  NULL,
    [ClosePriceDiffLgMax]          DECIMAL (38, 5)  NULL,
    [HighPriceDiffLgMin]           DECIMAL (38, 5)  NULL,
    [HighPriceDiffLgMax]           DECIMAL (38, 5)  NULL,
    [LowPriceDiffLgMin]            DECIMAL (38, 5)  NULL,
    [LowPriceDiffLgMax]            DECIMAL (38, 5)  NULL,
    [CandleDiffFromLagMaxPivot]    BIGINT           NULL,
    [CandleDiffFromLagMinPivot]    BIGINT           NULL,
    [PivotToPivotMaxDegree]        FLOAT (53)       NULL,
    [PivotToPivotMinDegree]        FLOAT (53)       NULL,
    [PivotToCurrentMaxDegree]      FLOAT (53)       NULL,
    [PivotToCurrentMinDegree]      FLOAT (53)       NULL,
    [VolLagPercent]                DECIMAL (38, 4)  NULL,
    [RSI14]                        DECIMAL (38, 23) NULL,
    [RSI5]                         DECIMAL (38, 23) NULL,
    [ID]                           INT              NULL,
    [OBV]                          INT              NULL,
    [CCI]                          NUMERIC (38, 6)  NULL,
    [+Di14]                        DECIMAL (38, 6)  NULL,
    [-Di14]                        DECIMAL (38, 6)  NULL,
    [ADX]                          DECIMAL (38, 6)  NULL,
    [IsBiggerThanMaxPrice3]        INT              NOT NULL,
    [IsBiggerThanMaxPrice5]        INT              NOT NULL,
    [IsBiggerThanMaxPrice8]        INT              NOT NULL,
    [IsBiggerThanMaxPrice13]       INT              NOT NULL,
    [IsBiggerThanMaxPrice34]       INT              NOT NULL,
    [IsLessThanMinPrice3]          INT              NOT NULL,
    [IsLessThanMinPrice5]          INT              NOT NULL,
    [IsLessThanMinPrice8]          INT              NOT NULL,
    [IsLessThanMinPrice13]         INT              NOT NULL,
    [IsLessThanMinPrice34]         INT              NOT NULL,
    [ResistantDistanceMaxPrice3]   DECIMAL (38, 6)  NULL,
    [ResistantDistancePrice5]      DECIMAL (38, 6)  NULL,
    [ResistantDistancePrice8]      DECIMAL (38, 6)  NULL,
    [ResistantDistancePrice13]     DECIMAL (38, 6)  NULL,
    [ResistantDistancePrice34]     DECIMAL (38, 6)  NULL,
    [SupportDistanceMinPrice3]     DECIMAL (38, 6)  NULL,
    [SupportDistanceMinPrice5]     DECIMAL (38, 6)  NULL,
    [SupportDistanceMinPrice8]     DECIMAL (38, 6)  NULL,
    [SupportDistanceMinPrice13]    DECIMAL (38, 6)  NULL,
    [SupportDistanceMinPrice34]    DECIMAL (38, 6)  NULL,
    [SMA]                          DECIMAL (38, 5)  NULL,
    [EMA]                          DECIMAL (38, 5)  NULL,
    [DiffSmaEmaOverClosePrcnt]     DECIMAL (38, 5)  NULL,
    [IsSmaOveEma]                  BIT              NULL,
    [SmaDegree]                    DECIMAL (6, 4)   NULL,
    [EmaDegree]                    DECIMAL (6, 4)   NULL,
    [IsRed]                        INT              NOT NULL,
    [IsGreen]                      INT              NOT NULL,
    [_PriceRange]                  DECIMAL (38, 5)  NULL,
    [PriceRangeWidthPrcnt]         DECIMAL (38, 6)  NULL,
    [MiddleBodyPrice]              DECIMAL (38, 6)  NULL,
    [MiddleFullPrice]              DECIMAL (38, 6)  NULL,
    [ResistantDistancePrcnt]       DECIMAL (38, 6)  NULL,
    [SupportDistancePrcnt]         DECIMAL (38, 6)  NULL,
    [FloorToCieling]               DECIMAL (38, 5)  NULL,
    [CandleBodyRangeWidthPrcnt]    DECIMAL (38, 6)  NULL,
    [_CloseOpenPrcnt]              DECIMAL (38, 6)  NULL,
    [_HighCielingPrcnt]            DECIMAL (38, 6)  NULL,
    [_FloorLowPrcnt]               DECIMAL (38, 6)  NULL,
    [OneLagIsRed]                  INT              NULL,
    [OneLagIsGreen]                INT              NULL,
    [OneLagCandleCeiling]          DECIMAL (38, 5)  NULL,
    [OneLagCandleFloor]            DECIMAL (38, 5)  NULL,
    [OneLagHigh]                   DECIMAL (38, 5)  NULL,
    [OneLagLow]                    DECIMAL (38, 5)  NULL,
    [OneCandleBodyRangeWidthPrcnt] DECIMAL (38, 6)  NULL,
    [OneFloorToCieling]            DECIMAL (38, 5)  NULL,
    [MonsterCandle_Bullish]        INT              NOT NULL,
    [MonsterCandle_Bearish]        INT              NOT NULL,
    [UHAMMER]                      INT              NOT NULL,
    [LHAMMER]                      INT              NOT NULL,
    [IsSharkZone]                  INT              NOT NULL
);

